name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Build & Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Prisma Migrate Deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npx prisma migrate deploy
          npx prisma db seed || echo "No seed configured"

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
        run: |
          echo "Triggering Render deploy..."
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d ''

      - name: Wait for backend to be live
        run: |
          echo "Waiting for backend..."
          until curl -s https://runner-city-backend.onrender.com/ping; do
            echo "Backend not ready, retrying in 5s..."
            sleep 5
          done
          echo "Backend is live!"
